# CodeBuild buildspec for Terraform apply
# Triggered by CodePipeline on CodeCommit push
#
# Required CodeBuild env vars (or set in Pipeline):
#   TF_STATE_BUCKET      - S3 bucket for Terraform state
#   TF_STATE_KEY         - State file key (e.g. mongotf/terraform.tfstate)
#   TF_STATE_LOCK_TABLE  - DynamoDB table for state locking
#   TF_VAR_aws_account_id
#   TF_VAR_mongodb_root_password (or from SSM)
#
# Optional: APPROVE_APPLY=true for auto-apply (main), false to only plan
# Optional: ROTATE_MONGODB_PASSWORD=true to run SSM Run Command on EC2 and set MongoDB password to the value in Parameter Store (see CICD.md)
# When cicd/* changes and cicd state is in S3, cicd stack is applied first (pipeline/CodeBuild updates).

version: 0.2

phases:
  pre_build:
    commands:
      - echo "Terraform version"
      - terraform version
      # If cicd/ changed, apply cicd first (pipeline/CodeBuild); requires cicd state migrated to S3 (see CICD.md)
      - |
        if git diff --name-only HEAD~1 HEAD 2>/dev/null | grep -q '^cicd/'; then
          echo "cicd/ changed — applying cicd stack first..."
          (cd cicd && terraform init -input=false \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="key=cicd/terraform.tfstate" \
            -backend-config="dynamodb_table=${TF_STATE_LOCK_TABLE}" \
            -backend-config="region=${AWS_REGION}" && \
            terraform apply -input=false -auto-approve) || echo "CICD apply skipped (e.g. cicd state not in S3 yet)."
        else
          echo "No cicd/ changes — skipping cicd apply."
        fi
      - echo "Initializing Terraform with S3 backend..."
      - |
        terraform init \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="key=${TF_STATE_KEY}" \
          -backend-config="dynamodb_table=${TF_STATE_LOCK_TABLE}" \
          -backend-config="region=${AWS_REGION}"
  build:
    commands:
      - echo "Running terraform validate..."
      - terraform validate
      - echo "Running terraform plan..."
      - terraform plan -out=tfplan -input=false
      - |
        if [ "$APPROVE_APPLY" = "true" ]; then
          echo "Auto-approve enabled. Applying changes..."
          terraform apply -input=false tfplan
        else
          echo "Apply skipped (APPROVE_APPLY != true). Plan saved."
        fi
      - |
        if [ "$APPROVE_APPLY" = "true" ] && [ "$ROTATE_MONGODB_PASSWORD" = "true" ]; then
          echo "ROTATE_MONGODB_PASSWORD enabled — syncing MongoDB password on instance via SSM..."
          aws ssm put-parameter --name /mongodb/MONGO_INITDB_ROOT_PASSWORD_NEW --value "$TF_VAR_mongodb_root_password" --type SecureString --overwrite --region "$AWS_REGION"
          INSTANCE_ID=$(terraform output -raw ec2_instance_id)
          SCRIPT_JSON=$(python3 -c "import json; print(json.dumps(open('scripts/rotate-mongodb-password.sh').read()))")
          echo "{\"commands\":[$SCRIPT_JSON]}" > /tmp/ssm-params.json
          CMD_ID=$(aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters file:///tmp/ssm-params.json --region "$AWS_REGION" --query Command.CommandId --output text)
          echo "Waiting for SSM command $CMD_ID..."
          for i in $(seq 1 30); do
            STATUS=$(aws ssm get-command-invocation --command-id "$CMD_ID" --instance-id "$INSTANCE_ID" --region "$AWS_REGION" --query Status --output text 2>/dev/null || echo "Pending")
            [ "$STATUS" = "Success" ] && break
            [ "$STATUS" = "Failed" ] && { aws ssm get-command-invocation --command-id "$CMD_ID" --instance-id "$INSTANCE_ID" --region "$AWS_REGION"; exit 1; }
            sleep 5
          done
          [ "$STATUS" != "Success" ] && { echo "SSM command timed out"; exit 1; }
          aws ssm get-command-invocation --command-id "$CMD_ID" --instance-id "$INSTANCE_ID" --region "$AWS_REGION" --query [Status,StandardOutputContent] --output text
          echo "MongoDB password rotation completed."
        fi
artifacts:
  files:
    - tfplan
  name: terraform-plan
cache:
  paths:
    - .terraform/**/*
