terraform {
  # Default: local state (no S3 bucket required). For remote state, use backend "s3" {} and run:
  #   terraform init -reconfigure -backend-config=backend.hcl
  # (create backend.hcl from backend.hcl.example and create the S3 bucket first.)
  backend "local" {
    path = "terraform.tfstate"
  }
  # backend "s3" {}

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.40.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "2.5"
    }
  }

  required_version = ">= 1.5.0"
}

provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}

# Prefix for resource names: dev_, stage_, or prod_ (from environment in tfvars)
locals {
  env_prefix  = var.environment == "staging" ? "stage" : (var.environment == "prod" ? "prod" : "dev")
  name_prefix = "${local.env_prefix}_"
  ssm_path    = "/mongodb/${local.env_prefix}"
}

check "aws_account_match" {
  assert {
    condition     = data.aws_caller_identity.current.account_id == var.aws_account_id
    error_message = "AWS account ID mismatch: terraform.tfvars has aws_account_id = \"${var.aws_account_id}\" but current credentials resolve to account \"${data.aws_caller_identity.current.account_id}\"."
  }
}

data "aws_availability_zones" "available" {}

# Default VPC
data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

# Latest Amazon Linux 2023 AMI (required for MongoDB 8.2 repo)
data "aws_ami" "amazon_linux_2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "state"
    values = ["available"]
  }
}

# Parameter store (paths are per-environment: /mongodb/dev, /mongodb/stage, /mongodb/prod)

resource "aws_ssm_parameter" "mongodb_secret_password" {
  name  = "${local.ssm_path}/MONGO_INITDB_ROOT_PASSWORD"
  type  = "SecureString"
  value = var.mongodb_root_password

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "mongodb_root_username" {
  name  = "${local.ssm_path}/MONGO_INITDB_ROOT_USERNAME"
  type  = "String"
  value = var.mongodb_root_username
}

# EC2 instance profile - SSM access for MongoDB auth setup
resource "aws_iam_role" "ec2_mongo_role" {
  name = "${local.name_prefix}ec2-mongo-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "ec2.amazonaws.com"
        }
      }
    ]
  })
}

resource "aws_iam_role_policy" "ec2_ssm_access" {
  name   = "${local.name_prefix}ec2-ssm-mongodb"
  role   = aws_iam_role.ec2_mongo_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "ssm:GetParameter",
          "ssm:GetParameters"
        ]
        Resource = [
          aws_ssm_parameter.mongodb_secret_password.arn,
          aws_ssm_parameter.mongodb_root_username.arn
        ]
      },
      {
        Effect = "Allow"
        Action = "kms:Decrypt"
        Resource = "*"
      }
    ]
  })
}

resource "aws_iam_instance_profile" "ec2_mongo" {
  name = "${local.name_prefix}ec2-mongo-profile"
  role = aws_iam_role.ec2_mongo_role.name
}

resource "aws_security_group" "ec2_sg" {
  name        = "${local.name_prefix}ec2_sg"
  description = "Security group for EC2 instance"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = var.ssh_allowed_cidrs
  }

  ingress {
    from_port   = 27017
    to_port     = 27017
    protocol    = "tcp"
    cidr_blocks = var.mongodb_allowed_cidrs
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# EC2 instance - SSH key (generated by Terraform if you don't have one)

resource "tls_private_key" "mongo" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "ec2_keypair" {
  key_name   = "${local.name_prefix}${var.key_pair_name}"
  public_key = tls_private_key.mongo.public_key_openssh
}

resource "local_file" "mongo_private_key" {
  content         = tls_private_key.mongo.private_key_pem
  filename        = "${path.module}/${local.name_prefix}mongo-key.pem"
  file_permission = "0600"
}

resource "aws_eip" "mongo" {
  domain = "vpc"
  tags = {
    Name = "mongolab-eip-${var.environment}"
  }
}

# EBS volume for MongoDB data (MongoDB WiredTiger does not support EFS/NFS)
data "aws_subnet" "ec2_subnet" {
  id = tolist(data.aws_subnets.default.ids)[0]
}
resource "aws_ebs_volume" "mongodb_data" {
  availability_zone = data.aws_subnet.ec2_subnet.availability_zone
  size              = var.ec2_mongodb_volume_size
  type              = "gp3"
  encrypted         = true

  tags = {
    Name = "mongolab-mongodb-data-${var.environment}"
  }
}

resource "aws_instance" "mongolab_ec2_instance" {
  ami                  = var.ec2_ami != "" ? var.ec2_ami : data.aws_ami.amazon_linux_2023.id
  instance_type        = var.ec2_instance_type
  subnet_id            = tolist(data.aws_subnets.default.ids)[0]
  key_name             = aws_key_pair.ec2_keypair.key_name
  iam_instance_profile = aws_iam_instance_profile.ec2_mongo.name

  security_groups = [aws_security_group.ec2_sg.id]

  user_data = templatefile("${path.module}/user-data.sh", {
    aws_region     = var.aws_region
    ssm_path_base = local.ssm_path
  })

  root_block_device {
    volume_size           = var.ec2_root_volume_size
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  tags = {
    Name        = "mongolab-mongodb-${var.environment}"
    Role        = "mongodb"
    Environment = var.environment
  }
}

resource "aws_volume_attachment" "mongodb_data" {
  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.mongodb_data.id
  instance_id = aws_instance.mongolab_ec2_instance.id
}

resource "aws_eip_association" "mongo" {
  instance_id   = aws_instance.mongolab_ec2_instance.id
  allocation_id = aws_eip.mongo.id
}

# EC2 health check: CloudWatch alarm on status check failures (system + instance reachability)
resource "aws_cloudwatch_metric_alarm" "mongodb_ec2_health" {
  alarm_name          = "mongolab-ec2-health-${var.environment}"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "StatusCheckFailed"
  namespace           = "AWS/EC2"
  period              = 60
  statistic           = "Maximum"
  threshold           = 0

  dimensions = {
    InstanceId = aws_instance.mongolab_ec2_instance.id
  }

  alarm_description = "MongoDB EC2 instance status check failed (system or instance unreachable)"
  alarm_actions      = var.ec2_health_alarm_sns_topic_arn != null ? [var.ec2_health_alarm_sns_topic_arn] : []
  treat_missing_data = "breaching"
}

output "ssh_private_key_path" {
  description = "Path to the generated SSH private key for EC2 access"
  value       = local_file.mongo_private_key.filename
}

output "ec2_public_ip" {
  description = "Static public IP of the MongoDB EC2 instance (Elastic IP)"
  value       = aws_eip.mongo.public_ip
}

output "ec2_instance_id" {
  description = "EC2 instance ID (use for AWS Backup or other automation)"
  value       = aws_instance.mongolab_ec2_instance.id
}

output "ebs_volume_id" {
  description = "MongoDB data EBS volume ID (attached to the EC2 instance)"
  value       = aws_ebs_volume.mongodb_data.id
}

output "ec2_ami_used" {
  description = "AMI ID used for the EC2 instance"
  value       = aws_instance.mongolab_ec2_instance.ami
}

output "mongodb_connection_string" {
  description = "MongoDB connection string (with auth)"
  value       = "mongodb://${var.mongodb_root_username}:<PASSWORD>@${aws_eip.mongo.public_ip}:27017"
}

# Write outputs to outputs/<env_prefix>_outputs.json on every apply (pretty-printed).
locals {
  outputs_map = {
    environment              = var.environment
    ssh_private_key_path     = local_file.mongo_private_key.filename
    ec2_public_ip            = aws_eip.mongo.public_ip
    ec2_instance_id          = aws_instance.mongolab_ec2_instance.id
    ebs_volume_id            = aws_ebs_volume.mongodb_data.id
    ec2_ami_used             = aws_instance.mongolab_ec2_instance.ami
    mongodb_connection_string = "mongodb://${var.mongodb_root_username}:<PASSWORD>@${aws_eip.mongo.public_ip}:27017"
  }
  # Pretty-print: newlines and spaces for readability (flat object only).
  _raw   = jsonencode(local.outputs_map)
  _nl    = replace(replace(replace(local._raw, "{\"", "{\n  \""), ",\"", ",\n  \""), "\"}", "\"\n}")
  outputs_json = replace(replace(local._nl, "\":\"", "\": \""), "\",\"", "\", \"")
}

resource "local_file" "outputs_json" {
  content         = local.outputs_json
  filename        = "${path.module}/outputs/${local.env_prefix}_outputs.json"
  file_permission = "0644"
}

output "outputs_file" {
  description = "Path to the generated outputs JSON file"
  value       = local_file.outputs_json.filename
}
