#!/usr/bin/env sh
# Create MongoDB infra with Terraform. Uses terraform.tfvars or env vars.
# Mac/Linux: run directly. Windows: use Git Bash or WSL, or run create-mongo-infra.ps1.
#
# Env vars (optional; if set, script writes terraform.tfvars and runs Terraform):
#   AWS_ACCOUNT_ID    - 12-digit AWS account ID
#   MONGO_USERNAME    - MongoDB root username (default: mongolabadmin)
#   MONGO_DB_NAME     - MongoDB database name (default: mongolab)
#   MONGO_PASSWORD    - MongoDB root password (stored in SSM on apply)
#   MONGO_ENVIRONMENT - dev, staging, or prod (prefixes resources: dev_, stage_, prod_)
#   AWS_REGION        - AWS region (default: eu-central-1)
#   AUTO_APPROVE      - set to 1 or true to run terraform apply -auto-approve (no prompt)
#
# If terraform.tfvars already exists, env vars are ignored and Terraform runs with existing tfvars.

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TFVARS="$PROJECT_ROOT/terraform.tfvars"

cd "$PROJECT_ROOT"

if [ -n "$AWS_ACCOUNT_ID" ] && [ -n "$MONGO_PASSWORD" ] && [ -n "$MONGO_ENVIRONMENT" ]; then
  # Write terraform.tfvars from env
  USERNAME="${MONGO_USERNAME:-mongolabadmin}"
  DBNAME="${MONGO_DB_NAME:-mongolab}"
  REGION="${AWS_REGION:-eu-central-1}"
  ENV="$MONGO_ENVIRONMENT"
  echo "Writing terraform.tfvars from env (environment=$ENV, account=$AWS_ACCOUNT_ID)."
  cat > "$TFVARS" << TFVARS_END
# Generated by create-mongo-infra.sh from env
aws_account_id = "$AWS_ACCOUNT_ID"
aws_region     = "$REGION"
environment    = "$ENV"

mongodb_root_username = "$USERNAME"
mongodb_root_password = "$MONGO_PASSWORD"
mongodb_database      = "$DBNAME"

ssh_allowed_cidrs     = ["0.0.0.0/0"]
mongodb_allowed_cidrs = ["0.0.0.0/0"]

ec2_instance_type        = "t2.micro"
ec2_mongodb_volume_size  = 20
key_pair_name = "mongolabkey"
mongo_image   = "mongo:latest"
log_retention_days = 30
ecs_task_cpu       = "256"
ecs_task_memory    = "512"
TFVARS_END
elif [ ! -f "$TFVARS" ]; then
  echo "Error: terraform.tfvars not found. Either:" 1>&2
  echo "  1. Copy terraform.tfvars.example to terraform.tfvars and edit it, or" 1>&2
  echo "  2. Set env vars: AWS_ACCOUNT_ID, MONGO_PASSWORD, MONGO_ENVIRONMENT (and optionally MONGO_USERNAME, MONGO_DB_NAME, AWS_REGION)" 1>&2
  exit 1
fi

if ! command -v terraform >/dev/null 2>&1; then
  echo "Error: terraform not found. Install Terraform and ensure it is on PATH." 1>&2
  exit 1
fi

echo "Running Terraform init..."
# Default backend in main.tf is local (no S3 required). -reconfigure avoids using old S3 backend if .terraform exists.
terraform init -reconfigure
echo "Running Terraform apply..."
case "$AUTO_APPROVE" in 1|true|yes|y) terraform apply -auto-approve ;; *) terraform apply ;; esac
