# Create MongoDB infra with Terraform. Uses terraform.tfvars or env vars.
# Run on Windows: .\scripts\create-mongo-infra.ps1
#
# Env vars (optional; if set, script writes terraform.tfvars and runs Terraform):
#   AWS_ACCOUNT_ID    - 12-digit AWS account ID
#   MONGO_USERNAME    - MongoDB root username (default: mongolabadmin)
#   MONGO_DB_NAME     - MongoDB database name (default: mongolab)
#   MONGO_PASSWORD    - MongoDB root password (stored in SSM on apply)
#   MONGO_ENVIRONMENT - dev, staging, or prod (prefixes resources: dev_, stage_, prod_)
#   AWS_REGION        - AWS region (default: eu-central-1)
#   AUTO_APPROVE      - set to 1 or true to run terraform apply -auto-approve (no prompt)
#
# If terraform.tfvars already exists, env vars are ignored.

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$Tfvars = Join-Path $ProjectRoot "terraform.tfvars"

Set-Location $ProjectRoot

if ($env:AWS_ACCOUNT_ID -and $env:MONGO_PASSWORD -and $env:MONGO_ENVIRONMENT) {
    $username = if ($env:MONGO_USERNAME) { $env:MONGO_USERNAME } else { "mongolabadmin" }
    $dbname   = if ($env:MONGO_DB_NAME)  { $env:MONGO_DB_NAME }  else { "mongolab" }
    $region   = if ($env:AWS_REGION)     { $env:AWS_REGION }     else { "eu-central-1" }
    $envName  = $env:MONGO_ENVIRONMENT
    Write-Host "Writing terraform.tfvars from env (environment=$envName, account=$env:AWS_ACCOUNT_ID)."
    $content = @"
# Generated by create-mongo-infra.ps1 from env
aws_account_id = "$env:AWS_ACCOUNT_ID"
aws_region     = "$region"
environment    = "$envName"

mongodb_root_username = "$username"
mongodb_root_password = "$env:MONGO_PASSWORD"
mongodb_database      = "$dbname"

ssh_allowed_cidrs     = ["0.0.0.0/0"]
mongodb_allowed_cidrs = ["0.0.0.0/0"]

ec2_instance_type        = "t2.micro"
ec2_mongodb_volume_size  = 20
key_pair_name = "mongolabkey"
mongo_image   = "mongo:latest"
log_retention_days = 30
ecs_task_cpu       = "256"
ecs_task_memory    = "512"
"@
    $content | Set-Content -Path $Tfvars -Encoding UTF8
} elseif (-not (Test-Path $Tfvars)) {
    Write-Error @"
terraform.tfvars not found. Either:
  1. Copy terraform.tfvars.example to terraform.tfvars and edit it, or
  2. Set env vars: `$env:AWS_ACCOUNT_ID, `$env:MONGO_PASSWORD, `$env:MONGO_ENVIRONMENT
     (optional: MONGO_USERNAME, MONGO_DB_NAME, AWS_REGION)
"@
    exit 1
}

if (-not (Get-Command terraform -ErrorAction SilentlyContinue)) {
    Write-Error "terraform not found. Install Terraform and ensure it is on PATH."
    exit 1
}

Write-Host "Running Terraform init..."
terraform init
Write-Host "Running Terraform apply..."
if ($env:AUTO_APPROVE -match "^(1|true|yes|y)$") { terraform apply -auto-approve } else { terraform apply }
